### PR TITLE
circumvented decoding error: “Expected Date, got String”

### PR DESCRIPTION
**Pull request by mihaelamj**
* There was a small decoding error, and now the UI works

### CODE REVIEW

**Comment by subdigital** [comment]
Thanks for letting me know! The proper way to resolve this however is by specifying a `dateDecodingStrategy` on the `JSONDecoder`.

```swift
let formatter = DateFormatter()
// the dates look like 2020-05-10, so we use a date format that can recognize this
formatter.dateFormat = "yyyy-MM-dd"

let decoder = JSONDecoder()
decoder.dateDecodingStrategy = .formatted(formatter)
```

Using this decoder we can decode the release date field properly.

**Comment by mihaelamj** [comment]
There was this code:
` decoder.dateDecodingStrategy = .formatted(Movie.releaseDateFormatter)`
And it didn't apply.

**Comment by mihaelamj** [comment]
The `decoder` of the `Movie` model is not called. I will look at that. Thnx

**Comment by subdigital** [comment]
@mihaelamj The underlying problem turned out that `PagedResults` had its own decoder and was being used instead of `Movie`'s decoder.

I've changed this to have `PagedResults` to just defer to it's generic `Item`'s decoder, which now allows this to work.

@mihaelamj Thanks for bringing this issue up!

**Pull request closed without merging**
